#!/usr/bin/env bash

# run all executables in the rootgit named *.rootgit

if [[ -z "$1" ]]; then
    echo "usage: $0 <rootgit directory>"
    exit 1
fi

cd $1
if [[ $? != "0" ]]; then
    echo "rootgit dir $1 inaccessible"
    exit 1
fi

rgdir=$(pwd)

rootgit_scripts=$(find -type f -executable -name '*.rootgit')

for s in $rootgit_scripts; do
    cd "$(dirname $s)"
    "$rgdir/$s"
    cd "$rgdir"
done

